INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('SvarTechInvest', 'Saint-Petersburg', 'Reselling');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('UralTermoSvar', 'Yekaterinburg', 'Welding Equipment Production');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('GlobalStroiIngeneering', 'Nizhnii Novgorod', 'Pipeline Petroleum Transportation');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('KazanEnergoRemont', 'Kazan', 'Energy Generation Equipment Maintenance');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('TSK', 'Moscow', 'Reselling');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('TMZ', 'Tikhvin', 'Mechanical Engeneering');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('RFYAC', 'Moscow', 'Engeneering services');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('SakhalinEnergo', 'Sakhalin', 'Energy Generation Equipment Maintenance');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('GazpromTransgazJugorsk', 'Jugorsk', 'Pipline gas transportation');
INSERT INTO customers(ORGANISATION, CITY, INDUSTRY) VALUES('Uralmash', 'Yekaterinburg', 'Mechanical Engeneering');

INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(1, 'Ivanov Dmitriy', 'telephone', '88121234567', false);
INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(1, 'Ivanov Dmitriy', 'email', 'ivanov@svartech.ru', true);
INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(1, 'Arsentev Petr', 'email', 'rpa@svartech.ru', false);
INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(2, 'Ezdakov Yuriy', 'telephone', '83437654321', true);
INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(3, 'Dukin Vladimir', 'telephone', '88317654321', true);
INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(4, 'Davletov Fanis', 'email', 'davletov@kazanenergo.ru', true);
INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(9, 'Vishemirskiy Fedor', 'email', 'vishemirskiy@transgazyugorsk.ru', true);
INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(7, 'Petrov Sergei', 'telephone', '8495999888777', true);
INSERT INTO contacts_info(CUSTOMER_ID, NAME, TYPE, DETAILS, PREFERRED) VALUES(7, 'Petrov Sergei', 'email', 'petrov@rfyaz.ru', false);

INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(1, 1, 2024-01-10, 'payment', 'received 2_500_000');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(1, 1, 2024-01-15, 'shipment', '30 kW');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(1, 3, 2024-02-20, 'shipment', '30 kW');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(2, 4, 2024-03-02, 'negotiations', 'discussing future deals');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(3, 5, 2024-03-03, 'discussion at equipment exhibition', 'product demonstration');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(2, 4, 2024-03-10, 'shipment', '50 kW');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(2, 4, 2024-03-15, 'shipment', '30 kW');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(2, 4, 2024-03-20, 'shipment', '30 kW');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(2, 4, 2024-03-25, 'shipment', '100 kW');
INSERT INTO interactions(CUSTOMER_ID, CONTACT_ID, DATE, TYPE, NOTES) VALUES(2, 4, 2024-03-27, 'payment', 'received_10_000_000');
